import {defineConfig} from '@playwright/test';
const env={LARA_MODE:'demo',APP_BASE_URL:'http://127.0.0.1:3015',API_INTERNAL_URL:'http://127.0.0.1:4014',OIDC_ISSUER:'https://identity.invalid',OIDC_CLIENT_ID:'browser-fixture',OIDC_CLIENT_SECRET:'browser-fixture',OIDC_REDIRECT_URI:'http://127.0.0.1:3015/auth/callback',SESSION_SECRET:'browser-fixture-session-key-32-characters',SESSION_SECRET_REF:'local-file',SESSION_PREVIOUS_SECRET:'',SESSION_PREVIOUS_SECRET_REF:'',OBJECT_ADAPTER:'filesystem',OBJECT_BUCKET:'.local/e2e',OBJECT_REGION:'local',MAIL_ADAPTER:'local',EINVOICE_ADAPTER:'fixture',AI_ADAPTER:'fixture',RULE_PROFILE_ID:'fixture-test',DEMO_RESET_ENABLED:'false'};
const web={command:'node apps/web/node_modules/next/dist/bin/next start apps/web --hostname 127.0.0.1 --port 3015',url:'http://127.0.0.1:3015',reuseExistingServer:false,env};
const api={command:'node apps/api/src/server.mjs',url:'http://127.0.0.1:4014/health/ready',reuseExistingServer:false,env:{...env,API_PORT:'4014',DATABASE_URL:process.env.LARA_E2E_DATABASE_URL}};
// Production composition under test: LARA_MODE=local renders the real workspace over /v1.
const local={...env,LARA_MODE:'local',APP_BASE_URL:'http://127.0.0.1:3016',API_INTERNAL_URL:'http://127.0.0.1:4015',OIDC_REDIRECT_URI:'http://127.0.0.1:3016/auth/callback',OBJECT_BUCKET:'.local/e2e-workspace',FIELD_ENCRYPTION_KEY:'0'.repeat(63)+'1',RATE_LIMIT_WRITES_PER_MINUTE:'600',RATE_LIMIT_READS_PER_MINUTE:'2000',E2E_EINVOICE_KEY:'browser-signing-key',E2E_EINVOICE_CREDENTIALS:'000-111-222-333:secret'};
const localApi={command:'node apps/api/src/server.mjs',url:'http://127.0.0.1:4015/health/ready',reuseExistingServer:false,env:{...local,API_PORT:'4015',DATABASE_URL:process.env.LARA_E2E_DATABASE_URL}};
const localWeb={command:'node apps/web/node_modules/next/dist/bin/next start apps/web --hostname 127.0.0.1 --port 3016',url:'http://127.0.0.1:3016',reuseExistingServer:false,env:local};
export default defineConfig({testDir:'./tests/browser',use:{baseURL:'http://127.0.0.1:3015',browserName:'chromium'},outputDir:'.local/browser-results',webServer:process.env.LARA_E2E_DATABASE_URL?[api,web,localApi,localWeb]:web});
