"use client";
import {useEffect,useRef,useState, type ReactNode, type FormEvent} from 'react';
import {usePathname} from 'next/navigation';

type Row=Record<string,any>;
const nav=[['My work','/work'],['Overview','/overview'],['Money in','/sales/invoices'],['Money out','/purchases/bills'],['Payments','/payments'],['Reconcile','/bank/reconcile'],['Close','/close/2026-09'],['Compliance','/compliance'],['Reports','/reports'],['Evidence','/evidence'],['Scenarios','/demo/scenarios'],['Feedback','/feedback']];
const php=(value:string)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(value));
const cents=(value:string)=>/^\d{1,9}(\.\d{1,2})?$/.test(value)?Number(value.split('.')[0])*100+Number((value.split('.')[1]||'').padEnd(2,'0')):NaN;
const money=(value:number)=>(value/100).toFixed(2);
function invoicePreview(form:HTMLFormElement,count:number){let subtotal=0;for(let n=0;n<count;n++){const data=new FormData(form);const quantity=Number(data.get('quantity'+n)),unit=cents(String(data.get('unitPrice'+n)||''));if(!Number.isInteger(quantity)||quantity<=0||!Number.isFinite(unit))return null;subtotal+=unit*quantity;}const tax=Math.floor((subtotal*12+50)/100);return {subtotal:money(subtotal),tax:money(tax),total:money(subtotal+tax)};}
const input=(label:string,name:string,value='',type='text')=><label>{label}<input name={name} defaultValue={value} type={type} required/></label>;

function Editor({id,children,onSave,label='Save draft',autoSave=false}:{id:string,children:ReactNode,onSave:(data:Row)=>Promise<boolean>,label?:string,autoSave?:boolean}) {
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 const ref=useRef<HTMLFormElement>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false);
 useEffect(()=>{const saved=sessionStorage.getItem('lara-draft:'+id);if(saved&&ref.current){try{const values=JSON.parse(saved);for(const field of Array.from(ref.current.elements)){if(field instanceof HTMLInputElement||field instanceof HTMLTextAreaElement||field instanceof HTMLSelectElement){if(values[field.name]!==undefined)field.value=values[field.name];}}setDirty(true);}catch{}}},[id]);
 useEffect(()=>{if(!dirty)return;const leave=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(timer.current)clearTimeout(timer.current);setSaving(true);try{if(await onSave(Object.fromEntries(new FormData(e.currentTarget)))){sessionStorage.removeItem('lara-draft:'+id);setDirty(false);}}finally{setSaving(false);}}
 return <form ref={ref} className="demo-form" onSubmit={submit} onChange={()=>{setDirty(true);if(timer.current)clearTimeout(timer.current);if(autoSave)timer.current=setTimeout(()=>{if(ref.current?.checkValidity())ref.current.requestSubmit();},1800);if(ref.current)sessionStorage.setItem('lara-draft:'+id,JSON.stringify(Object.fromEntries(new FormData(ref.current))));}}>{children}<p role="status">{saving?'Saving…':dirty?'Unsaved draft retained in this browser tab.':'Draft is up to date.'}</p><button disabled={saving} type="submit">{label}</button>{dirty&&<button type="button" onClick={()=>{if(timer.current)clearTimeout(timer.current);ref.current?.reset();sessionStorage.removeItem('lara-draft:'+id);setDirty(false);}}>Discard local edits</button>}</form>;
}

export default function DemoWorkspace() {
 const path=usePathname(),[s,setState]=useState<Row|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[lineCount,setLineCount]=useState(1);
 const pending=useRef<Row|null>(null);
 const [fromDate,setFromDate]=useState(''),[toDate,setToDate]=useState('');
 const [preview,setPreview]=useState<{subtotal:string,tax:string,total:string}|null>(null);
 async function load(){try{const r=await fetch('/api/demo/workspace',{cache:'no-store'});const data=await r.json();if(!r.ok)throw Error(data.error);setState(data);setError('');return data;}catch(e){setError(e instanceof Error?e.message:'Connection interrupted. Retry when available.');return null;}}
 useEffect(()=>{void load();const url=new URL(window.location.href);setSearch(url.searchParams.get('q')||'');setStatus(url.searchParams.get('status')||'');setFromDate(url.searchParams.get('from')||'');setToDate(url.searchParams.get('to')||'');},[]);
 const remember=(next:Record<string,string>)=>{const url=new URL(window.location.href);for(const [k,v] of Object.entries({q:search,status,from:fromDate,to:toDate,...next})){if(v)url.searchParams.set(k,v);else url.searchParams.delete(k);}history.replaceState(null,'',url.pathname+url.search);};
 async function send(b:Row){setBusy(true);setError('');try{const r=await fetch('/api/demo/command',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b)});const data=await r.json();if(!r.ok){if(r.status<500)pending.current=null;throw Error(data.error);}pending.current=null;setMessage(data.message);await load();return data;}catch(e){setError(e instanceof Error?e.message:'Connection interrupted.');return null;}finally{setBusy(false);}}
 async function act(action:string,fields:Row={}){if(!s||busy)return null;const b={...fields,action,run:s.run,version:s.version,key:crypto.randomUUID()};pending.current=b;return send(b);}
 const save=(action:string,fields:Row={})=>async(data:Row)=>!!await act(action,{...fields,...data});
 const permitted=(roles:string[])=>!!s&&roles.includes(s.actor);
 const action=(label:string,name:string,roles:string[],fields:Row={})=><button disabled={busy||!permitted(roles)||(name==='lock-period'&&!s?.period.tasks.every((t:Row)=>t.complete&&t.evidence))} title={permitted(roles)?label:`Switch to ${roles.join(' or ')} in Scenarios`} onClick={()=>void act(name,fields)}>{label}</button>;
 const table=(head:string[],rows:ReactNode[][])=><div className="table-scroll" tabIndex={0} role="region" aria-label={head.join(', ')+' table'}><table><thead><tr>{head.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>No records yet. Choose a scenario or create your first draft.</p>}</div>;
 const link=(href:string,label:string)=><a href={href}>{label}</a>;
 const id=path.split('/').at(-1)!;
 let title=nav.find(([,href])=>path===href)?.[0]||'Workspace';let content:ReactNode=null;
 if(s){
 const invoice=s.invoices.find((r:Row)=>r.id===id),bill=s.bills.find((r:Row)=>r.id===id),payment=s.payments.find((r:Row)=>r.id===id);
 if(path==='/'||path==='/overview'){
 title='Your synthetic finance workspace';content=<><p>As of 18 September 2026 · Asia/Manila. Balances are derived from simulated journal events.</p><div className="overview-grid">{['Bank','Accounts receivable','Accounts payable'].map(a=><article key={a}><span>{a}</span><strong>{php(s.balances.find((b:Row)=>b.account===a)?.balance||'0.00')}</strong>{link('/reports','Inspect source events')}</article>)}</div><p>{s.tasks.filter((t:Row)=>t.status==='Open').length} open tasks · {s.reporting.filter((r:Row)=>r.status!=='Accepted').length} reporting blockers · {s.lines.filter((l:Row)=>l.status!=='Matched').length} unreconciled lines</p><div className="action-row">{link('/work','Open my work')}{link('/sales/invoices/new','Create an invoice')}{link('/demo/scenarios','Choose a scenario')}</div></>;
 }else if(path==='/work'){
 content=<><label>Filter tasks<input value={search} onChange={e=>setSearch(e.target.value)}/></label>{table(['Task','Owner','Due','Amount','Assign'],s.tasks.filter((t:Row)=>(t.title+' '+t.owner).toLowerCase().includes(search.toLowerCase())).map((t:Row)=>[link(t.source,t.title),t.owner,t.due,php(t.amount),<select aria-label={'Assign '+t.title} value={t.owner} disabled={!permitted(['Controller'])||busy} onChange={e=>void act('assign-task',{id:t.id,owner:e.target.value})}>{s.actors.map((a:string)=><option key={a}>{a}</option>)}</select>]))}</>;
 }else if(path==='/sales/invoices'){
 title='Sales invoices';content=<><a className="button" href="/sales/invoices/new">Create invoice</a><div className="filter-row"><label>Search customer<input value={search} onChange={e=>{setSearch(e.target.value);remember({q:e.target.value});}}/></label><label>Status<select value={status} onChange={e=>{setStatus(e.target.value);remember({status:e.target.value});}}><option value="">All</option>{['Draft','Submitted','Approved','Posted'].map(x=><option key={x}>{x}</option>)}</select></label><label>Issued from<input type="date" value={fromDate} onChange={e=>{setFromDate(e.target.value);remember({from:e.target.value});}}/></label><label>Issued through<input type="date" value={toDate} onChange={e=>{setToDate(e.target.value);remember({to:e.target.value});}}/></label></div>{table(['Customer','Issue date','Total','Workflow','Settlement'],s.invoices.filter((i:Row)=>i.customer.toLowerCase().includes(search.toLowerCase())&&(!status||i.status===status)&&(!fromDate||i.issueDate>=fromDate)&&(!toDate||i.issueDate<=toDate)).map((i:Row)=>[link('/sales/invoices/'+i.id,i.customer),i.issueDate,php(i.total),i.status,i.settlement]))}</>;
 }else if(path==='/sales/invoices/new'||invoice){
 title=invoice?invoice.customer:'New invoice';const editable=!invoice||['Draft','Submitted','Approved'].includes(invoice.status);
 content=<>{invoice&&<><p>Workflow: {invoice.status} · Delivery: {invoice.delivery} · Reporting: {invoice.reporting} · Settlement: {invoice.settlement}</p><p>Total {php(invoice.total)} · {invoice.number||'No simulated number yet'}</p>{invoice.correctionOf&&link('/sales/invoices/'+invoice.correctionOf,'Original source')}<div className="action-row">{invoice.status==='Draft'&&action('Submit invoice','submit-invoice',['Billing','Clerk'],{id})}{invoice.status==='Submitted'&&action('Approve invoice','approve-invoice',['Reviewer','Controller'],{id})}{invoice.status==='Approved'&&action('Simulate posting','post-invoice',['Reviewer','Controller'],{id})}{invoice.status==='Posted'&&invoice.settlement==='Unpaid'&&action('Record collection','collect-invoice',['Treasury'],{id})}{invoice.status==='Posted'&&action('Create linked correction','correct-invoice',['Billing','Tax'],{id})}</div></>}{editable&&<Editor id={s.run+path} autoSave={!!invoice} onSave={async d=>{const lines=Array.from({length:Math.max(lineCount,invoice?.lines.length||1)},(_,i)=>({description:d['description'+i],quantity:d['quantity'+i],unitPrice:d['unitPrice'+i]}));const r=await act('save-invoice',{...d,lines,...(invoice?{id}:{} )});if(r?.id){setMessage('Invoice saved.');window.setTimeout(()=>window.location.assign('/sales/invoices/'+r.id),100);}return !!r;}}>{input('Customer','customer',invoice?.customer||'')}{input('Issue date','issueDate',invoice?.issueDate||'2026-09-18','date')}{input('Due date','dueDate',invoice?.dueDate||'2026-10-18','date')}<div onBlur={e=>{const form=e.currentTarget.closest('form');if(form)setPreview(invoicePreview(form,Math.max(lineCount,invoice?.lines.length||1)));}}>{Array.from({length:Math.max(lineCount,invoice?.lines.length||1)},(_,n)=><fieldset key={n}><legend>Line {n+1}</legend>{input('Description','description'+n,invoice?.lines[n]?.description||'Services')}{input('Quantity','quantity'+n,String(invoice?.lines[n]?.quantity||1),'number')}{input('Unit price PHP','unitPrice'+n,invoice?.lines[n]?.unitPrice||'10000.00')}</fieldset>)}</div><button type="button" onClick={()=>setLineCount(Math.max(lineCount,invoice?.lines.length||1)+1)}>Add line</button>{input('Terms','terms',invoice?.terms||'30 days')}<p role="status" aria-live="polite">{preview?`Amount preview: subtotal ${php(preview.subtotal)} · test VAT ${php(preview.tax)} · total ${php(preview.total)}`:invoice?`Saved amount: ${php(invoice.total)}`:'Amount preview appears after you leave a quantity or unit price field.'}</p><p>Draft changes autosave after the first save. Simulated test VAT: 12%. This fixture does not establish legal tax applicability.</p></Editor>}{link('/sales/invoices','Back to invoices')}</>;
 }else if(path==='/purchases/bills'){
 title='Supplier bills';content=table(['Supplier','Total','Review','Source'],s.bills.map((b:Row)=>[link('/purchases/bills/'+b.id,b.supplier),php(b.amount),b.status,link('/evidence/'+b.evidence,'Inspect evidence')]));
 }else if(bill){
 title=bill.supplier;content=<><div className="split-panel"><section><h2>Simulated extraction</h2><p>Confidence {bill.confidence} · Low confidence: supplier TIN</p><pre>{s.evidence.find((e:Row)=>e.id===bill.evidence)?.content}</pre>{link('/evidence/'+bill.evidence,'Open source evidence')}</section><section><h2>Review draft</h2><p>Status: {bill.status} · {php(bill.amount)}</p>{bill.status!=='Posted'&&<Editor id={s.run+path} onSave={save('save-bill',{id})}>{input('Synthetic supplier TIN','tin',bill.tin)}{input('Correction explanation','correction',bill.correction)}<label>Purchase route<select name="route" defaultValue={bill.route}><option>Non-PO</option><option>PO</option></select></label></Editor>}</section></div><div className="action-row">{bill.status==='Draft'&&action('Submit bill','submit-bill',['Clerk'],{id})}{bill.status==='Submitted'&&action('Approve bill','approve-bill',['Reviewer','Controller'],{id})}{bill.status==='Approved'&&action('Simulate bill posting','post-bill',['Reviewer','Controller'],{id})}{bill.status==='Posted'&&link('/payments','Open payment authority')}</div></>;
 }else if(path==='/payments'){
 content=table(['Beneficiary','Amount','Authority','Release','Settlement'],s.payments.map((p:Row)=>[link('/payments/'+p.id,p.beneficiary),php(p.amount),p.authority,p.release,p.settlement]));
 }else if(payment){
 title='Payment authority';content=<><p>Authority: {payment.authority} · Release: {payment.release} · Settlement: {payment.settlement}</p><p>{php(payment.amount)} · Simulated only: no real transfer.</p>{link('/purchases/bills/'+payment.bill,'Approved source bill')}{payment.release==='Not released'&&<><Editor id={s.run+path} onSave={save('save-payment',{id})}>{input('Beneficiary','beneficiary',payment.beneficiary)}<p>Changing this value invalidates approval.</p></Editor><div className="action-row">{action('Approve authority','approve-payment',['Reviewer','Controller'],{id})}{action('Simulate release','release-payment',['Treasury'],{id})}</div></>}</>;
 }else if(path==='/bank/reconcile'){
 title='Bank reconciliation';content=<>{link('/evidence/evidence-bank','Inspect imported fixture CSV')}{s.lines.map((l:Row)=><section className="demo-card" key={l.id}><h2>{l.description}</h2><p>{l.status} · Statement {php(l.amount)} · Remaining {php((Number(l.amount)-l.allocations.reduce((n:number,a:Row)=>n+Number(a.amount),0)).toFixed(2))}</p>{table(['Source','Amount','Adjustment'],l.allocations.map((a:Row)=>[a.source,php(a.amount),a.adjustment?'Explicit fee':'Receipt allocation']))}{l.status!=='Matched'&&<Editor id={s.run+l.id} label={l.id==='bank-fee'?'Record explicit fee adjustment':'Allocate receipt'} onSave={save('match-bank',{id:l.id,adjustment:l.id==='bank-fee'})}>{input('Allocation PHP','amount',l.id==='bank-fee'?'50.00':'11200.00')}{l.id!=='bank-fee'&&<label>Collected invoice<select name="source" required><option value="">Select a receipt</option>{s.invoices.filter((i:Row)=>i.settlement==='Paid').map((i:Row)=><option key={i.id} value={i.id}>{i.customer} · {php(i.total)}</option>)}</select></label>}</Editor>}</section>)}</>;
 }else if(path.startsWith('/close')){
 title='Close September 2026';content=<><p>{s.period.locked?'Locked · original report retained. Late posting is denied.':'Lock preview: complete both owned tasks with evidence first.'}</p>{s.period.tasks.map((t:Row)=><section className="demo-card" key={t.id}><h2>{t.title}</h2><p>{t.owner} · {t.complete?'Complete':'Open'}</p>{t.evidence&&link('/evidence/'+t.evidence,'Attached evidence')}{!t.complete&&<Editor id={s.run+t.id} label="Complete task" onSave={save('complete-close',{id:t.id})}><label>Evidence<select name="evidence">{s.evidence.filter((e:Row)=>e.status==='Available').map((e:Row)=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label></Editor>}</section>)}{!s.period.locked&&action('Lock synthetic period','lock-period',['Reviewer','Controller'])}{s.period.locked&&link('/reports','Inspect retained report')}</>;
 }else if(path==='/compliance'){
 title='Simulated reporting queue';content=<>{!s.reporting.length&&<p>Post an invoice to exercise the rejected reporting fixture.</p>}{s.reporting.map((r:Row)=><section key={r.id} className="demo-card"><h2>{r.status}</h2><p>{r.reason}</p>{link('/sales/invoices/'+r.source,'Return to original source')}{r.status!=='Accepted'&&<Editor id={s.run+r.id} label="Simulate transport repair" onSave={save('resolve-reporting',{id:r.id})}>{input('Buyer reference repair','repair')}</Editor>}<ul>{r.history.map((h:Row,i:number)=><li key={i}>{h.status}: {h.reason} · Repair: {h.repair}</li>)}</ul></section>)}</>;
 }else if(path==='/evidence'){
 content=table(['Evidence','Status','Related record'],s.evidence.filter((e:Row)=>e.title.toLowerCase().includes(search.toLowerCase())).map((e:Row)=>[link('/evidence/'+e.id,e.title),e.status,link(e.related,'Open source')]));
 }else if(path.startsWith('/evidence/')){
 const e=s.evidence.find((e:Row)=>e.id===id);title=e?.title||'Evidence not found';content=e?<><p>{e.status} · Synthetic evidence</p>{e.status==='Available'?<pre>{e.content}</pre>:<p>Preview unavailable while this fixture is quarantined.</p>}{link(e.related,'Related record')}</>:<p>This evidence is missing or outside your authorized session.</p>;
 }else if(path==='/reports'){
 title='Synthetic trial balance';const rows=s.period.locked?s.period.report:s.balances;content=<><p>SIMULATED · Not statutory books. {s.period.locked?'Retained at period lock.':'Current session balances.'}</p>{table(['Account','Debit PHP','Credit PHP'],rows.map((r:Row)=>[link('/reports/'+encodeURIComponent(r.account),r.account),php(r.debit),php(r.credit)]))}<button disabled={!permitted(['Auditor','Controller'])} onClick={async()=>{try{const r=await fetch('/api/demo/export');const data=await r.json();if(!r.ok)throw Error(data.error);const url=URL.createObjectURL(new Blob([data.content],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=data.filename;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:'Export unavailable.');}}}>Download simulated CSV</button></>;
 }else if(path.startsWith('/reports/')){
 title='Journal drill-through';const account=decodeURIComponent(id);content=table(['Number','Kind','Source','Evidence'],s.journals.filter((j:Row)=>j.lines.some((l:Row)=>l.account===account)).map((j:Row)=>[j.number,j.kind,link(s.invoices.some((i:Row)=>i.id===j.source)?'/sales/invoices/'+j.source:s.bills.some((i:Row)=>i.id===j.source)?'/purchases/bills/'+j.source:'/bank/reconcile','Open source'),link('/evidence/'+j.evidence,'Inspect evidence')]));
 }else if(path==='/settings/setup'){
 title='Setup checklist';content=permitted(['Controller'])?<Editor id={s.run+path} onSave={async d=>!!await act('save-settings',{...d,rolesReviewed:d.rolesReviewed==='yes'})}>{input('Organization','company',s.settings.company)}{input('Synthetic party','party',s.settings.party)}<label>Role checklist reviewed<select name="rolesReviewed" defaultValue={s.settings.rolesReviewed?'yes':'no'}><option value="no">Pending</option><option value="yes">Reviewed</option></select></label></Editor>:<p>Controller permission is required. Use the dedicated demo identity switch in Scenarios.</p>;
 }else if(path==='/demo/scenarios'){
 content=<><h2>Demo identity</h2><p>This switch changes only your synthetic actor. Your Supabase login remains the same.</p><label>Active actor<select value={s.actor} disabled={busy} onChange={e=>void act('switch-actor',{actor:e.target.value})}>{s.actors.map((a:string)=><option key={a}>{a}</option>)}</select></label><h2>Reset my session</h2><Editor id={s.run+path} label="Reset my synthetic session" onSave={async d=>window.confirm('Reset only your synthetic session? Existing records will no longer appear in this run.')?!!await act('reset',{...d,confirm:'RESET MY SYNTHETIC SESSION'}):false}><label>Scenario<select name="scenario" defaultValue={s.scenario}>{s.scenarios.map((x:Row)=><option key={x.id} value={x.id}>{x.id} · {x.title}</option>)}</select></label></Editor><p>Current scenario: {s.scenario}. Start in {s.actor}; switch demo identity when a task calls for a different role.</p><a href={s.scenario==='DEMO-02'?'/purchases/bills/bill-fixture':s.scenario==='DEMO-04'?'/compliance':s.scenario==='DEMO-05'?'/bank/reconcile':s.scenario==='DEMO-06'?'/close/2026-09':s.scenario==='DEMO-07'?'/reports':'/sales/invoices'}>Open scenario workspace</a><h2>Simulation legend</h2><p>Posting, tax, AI extraction, reporting and payments are deterministic fixtures. Drafts, comments, feedback and workflow state are persisted. No email, filing or bank transfer is sent.</p><ol>{s.scenarios.map((x:Row)=><li key={x.id}>{x.id} · {x.title}</li>)}</ol></>;
 }else if(path==='/feedback'){
 content=<Editor id={s.run+path} label="Record feedback" onSave={save('feedback')}><label>Scenario<select name="scenario">{s.scenarios.map((x:Row)=><option key={x.id}>{x.id}</option>)}</select></label>{input('Route','route','/work')}<label>Severity<select name="severity"><option>minor</option><option>major</option><option>blocking</option></select></label><label>Feedback<textarea name="text" required maxLength={2000}/></label></Editor>;
 }else{title='Record not found';content=<p>This record is unavailable in your current demo session.</p>;}
 if(invoice||bill||payment)content=<>{content}<h2>Comments</h2>{s.comments.filter((c:Row)=>c.source===id).map((c:Row)=><p key={c.id}>{c.actor}: {c.text}</p>)}<Editor id={s.run+path+'comment'} label="Add comment" onSave={save('comment',{id})}><label>Comment<textarea name="text" required maxLength={2000}/></label></Editor><h2>Timeline</h2><ol>{s.events.filter((e:Row)=>e.source===id).map((e:Row)=><li key={e.id}>{e.action} · {e.actor} · {new Date(e.at).toLocaleString('en-PH',{timeZone:'Asia/Manila'})}</li>)}</ol></>;
 }
 return <div className="lara-shell"><a className="skip-link" href="#workspace">Skip to content</a><aside className="lara-nav"><a href="/"><img src="/assets/lara/logos/lara-logo-reverse.svg" alt="LARA" width="144" height="40"/></a><p className="demo-badge">Demo · synthetic data</p><nav aria-label="Primary navigation">{nav.map(([label,url])=><a key={url} href={url} aria-current={path===url?'page':undefined}>{label}</a>)}{permitted(['Controller'])&&<a href="/settings/setup">Settings</a>}</nav></aside><div className="lara-content"><header className="lara-header"><div><strong>LARA Demo Finance</strong><p>September 2026 · Asia/Manila</p></div>{s?<><label>Branch<select value={s.branch} onChange={e=>{if(window.confirm('Save drafts before switching branch. Continue?'))void act('context',{branch:e.target.value}).then(r=>{if(r)window.location.assign('/overview');});}}><option>HQ</option><option>Cebu</option></select></label><span>{s.actor} · Demo identity</span><a href="/auth/logout">Sign out</a></>:<a className="button" href="/api/auth/login">Sign in</a>}</header><main id="workspace" className="workspace-page"><p className="eyebrow">Simulated workspace · persistent synthetic data</p><h1>{s?title:error?'Workspace unavailable':'Loading workspace…'}</h1>{error&&<section role="alert" className="error-panel"><p>{error}</p><button onClick={()=>void load()}>Reload latest workspace</button>{pending.current&&<button onClick={()=>void send(pending.current!)}>Retry the same command</button>}</section>}{message&&<p role="status">{message}</p>}{s?<fieldset className="workspace-actions" disabled={busy}>{content}</fieldset>:<p>Sign in with your provisioned Supabase demo account to continue.</p>}</main></div></div>;
}
