"use client";
// P07 compliance workbench: readiness with ready, failed and not-tested
// states per gate and per form, return runs prepared at a frozen cutoff with
// the return-to-ledger drill-down and filing evidence, the reporting queue
// with deadlines, rejection views that distinguish a financial correction
// from an envelope repair, and the registration pack. Nothing here files or
// transmits by itself: preparation, approval, filing and reconciliation are
// separate recorded steps.
import {useEffect,useState} from 'react';
import {api,asError,useCommand,ErrorPanel,Editor,table,link,useList,Loading,input,select,when,uuid,type Row,type ApiError} from './workspace-kit';
import {useBookId} from './workspace-ledger';

const money=(v:string|number|null|undefined)=>v==null?'—':new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP'}).format(Number(v));
const today=()=>new Date().toISOString().slice(0,10);
type Ctx={entityId:string,me:Row,can:(p:string)=>boolean,tick:number,refresh:()=>void};
function NotEnabled({me}:{me:Row}){return <section className="demo-card"><h2>Compliance not enabled</h2><p>The compliance capability is activated per entity after treasury, with an approved compliance profile (taxpayer identity, transport, deadline profile, key and credential references) and a regulatory profile whose official artifacts the tax lead approved. {me.permissions.includes('capability.activate')?<a href="/settings/capabilities">Open capabilities</a>:'Ask a controller to activate it.'}</p></section>;}
const Gate=({label,state}:{label:string,state:string})=><li><strong>{label}</strong> · <span className={'gate gate-'+state}>{state.replace('_',' ')}</span></li>;

export function ComplianceWorkbench({entityId,me,can,tick,refresh}:Ctx){
 if(!me.capabilities.includes('compliance'))return <NotEnabled me={me}/>;
 const [ready,setReady]=useState<Row|null>(null),[error,setError]=useState<ApiError|null>(null);
 useEffect(()=>{api('GET','/compliance/readiness',{entityId}).then(r=>{setReady(r.data);setError(null);}).catch(e=>setError(asError(e)));},[entityId,tick]);
 const returns=useList('/returns',entityId,tick);
 const queue=useList('/transmissions',entityId,tick);
 const evidence=useList('/evidence',entityId,tick,{status:'available'});
 const {bookId}=useBookId(entityId,tick,me);
 const cmd=useCommand(refresh);
 const [open,setOpen]=useState<string|null>(null),[lines,setLines]=useState<Row|null>(null);
 useEffect(()=>{if(!open){setLines(null);return;}api('GET','/returns/'+open+'/lines',{entityId}).then(r=>setLines(r.data)).catch(e=>setError(asError(e)));},[open,tick]);
 const act=(r:Row,label:string,path:string,body:Row,permission:string)=>can(permission)?<button key={path} disabled={cmd.busy} onClick={()=>void cmd.run('POST','/returns/'+r.id+'/'+path,{entityId,ifMatch:r.version,body})}>{label}</button>:null;
 const tact=(t:Row,label:string,path:string,permission:string)=>can(permission)?<Editor key={path} id={path+t.id+t.version} label={label} onSave={async d=>!!await cmd.run('POST','/transmissions/'+t.id+'/'+path,{entityId,ifMatch:t.version,body:{reason:d.reason}})}>{input('Reason','reason','','text',{required:true})}</Editor>:null;
 const [job,setJob]=useState<Row|null>(null);
 useEffect(()=>{if(!job||!['queued','running','retry_wait'].includes(job.state))return;const t=setTimeout(()=>api('GET','/jobs/'+job.id,{entityId}).then(r=>setJob(r.data)).catch(e=>setError(asError(e))),1500);return()=>clearTimeout(t);},[job]);
 return <>
  <ErrorPanel error={error||cmd.error||returns.error} onRetry={cmd.retry} onReload={cmd.reload} canRetry={cmd.canRetry}/>
  <section className="demo-card"><h2>Readiness</h2>{ready===null?<Loading/>:<><ul className="gates"><Gate label="Capability" state={ready.capability}/><Gate label="Compliance profile" state={ready.complianceProfile}/><Gate label="Regulatory profile (official artifacts)" state={ready.regulatoryProfile}/><Gate label="Signing key" state={ready.signingKey}/><Gate label="Taxpayer credentials" state={ready.credentials}/><Gate label="E-invoice schema artifact" state={ready.einvoiceSchema}/><li><strong>Transport</strong> · {ready.transport}{ready.transport==='fixture'?' (fixture; a provider adapter is a separate activation gate)':''}</li></ul>
   <h3>Forms</h3>{table(['Form','Jurisdiction','Mapping artifact'],ready.forms.map((f:Row)=>[f.code,f.jurisdiction,f.mapping.replace('_',' ')]),'No active regulatory profile names any form; nothing is enabled.')}<p>A form is enabled only with its reviewed mapping artifact; "not tested" forms cannot be prepared.</p></>}</section>
  {can('return.create')&&<section className="demo-card"><h2>New return run</h2><p>Preparation freezes the data cutoff and computes every line from the tax events of the period through the approved mapping; unmapped events block preparation rather than producing a plausible zero.</p><Editor id={'return-new'+entityId} label="Create run" resetOnSave onSave={async d=>!!await cmd.run('POST','/returns',{entityId,body:{formCode:d.formCode,periodStart:d.periodStart,periodEnd:d.periodEnd,profileVersion:d.profileVersion,dataCutoff:new Date().toISOString()}})}>
   {input('Form code','formCode','2550Q','text',{required:true,pattern:'[A-Za-z0-9][A-Za-z0-9._-]{0,31}'})}{input('Period start','periodStart',today().slice(0,8)+'01','date',{required:true})}{input('Period end','periodEnd',today(),'date',{required:true})}{input('Profile version','profileVersion','ph-2026','text',{required:true})}
  </Editor></section>}
  <h2>Return runs</h2>
  {returns.items===null?<Loading/>:table(['Form','Period','Cutoff','State','Actions'],returns.items.map(r=>[r.formCode,r.periodStart+' → '+r.periodEnd,when(r.dataCutoff),r.state,<div key="a" className="action-row"><button type="button" onClick={()=>setOpen(open===r.id?null:r.id)}>{open===r.id?'Hide lines':'Lines'}</button>{['draft','prepared'].includes(r.state)&&act(r,'Prepare','prepare',{},'return.prepare')}{r.state==='prepared'&&act(r,'Approve','approve',{decision:'approve',contentVersion:r.contentVersion},'return.approve')}{r.state==='prepared'&&can('return.approve')&&<Editor id={'rejr'+r.id} label="Reject" onSave={async d=>!!await cmd.run('POST','/returns/'+r.id+'/approve',{entityId,ifMatch:r.version,body:{decision:'reject',contentVersion:r.contentVersion,reason:d.reason}})}>{input('Reason','reason','','text',{required:true})}</Editor>}{r.state==='approved'&&can('return.filed')&&<Editor id={'file'+r.id} label="Record filing" onSave={async d=>!!await cmd.run('POST','/returns/'+r.id+'/filed',{entityId,ifMatch:r.version,body:{externalReference:d.externalReference,filedAt:new Date(d.filedAt+'T00:00:00Z').toISOString(),evidenceIds:[d.evidenceId]}})}>{input('Filing reference','externalReference','','text',{required:true})}{input('Filed on','filedAt',today(),'date',{required:true})}<label>Acknowledgement evidence<select name="evidenceId" required><option value="">Select evidence</option>{(evidence.items||[]).map((e:Row)=><option key={e.id} value={e.id}>{e.filename}</option>)}</select></label></Editor>}</div>]),'No return runs yet.')}
  {open&&<section className="demo-card"><h2>Return lines</h2>{lines===null?<Loading/>:<>{table(['Line','Description','Basis','Amount','Events'],lines.lines.map((l:Row)=>[l.lineCode,l.description,money(l.basis),money(l.amount),l.eventCount]),'Not prepared yet.')}<p>Total basis {money(lines.totalBasis)} · total amount {money(lines.totalAmount)} · snapshot {lines.snapshotHash?lines.snapshotHash.slice(0,12)+'…':'—'}</p>{lines.tieOut?.events!==undefined&&<p role="status">Tie-out: {lines.tieOut.events} source event(s) · source {money(lines.tieOut.sourceAmount)} · return {money(lines.tieOut.returnAmount)} · ledger {lines.tieOut.ledgerTaxMovement==null?'n/a':money(lines.tieOut.ledgerTaxMovement)} · {lines.tieOut.ties?'ties':'does not tie — approval records the reviewed difference'}</p>}{lines.filing&&<p>Filed {when(lines.filing.filedAt)} under {lines.filing.externalReference} with {lines.filing.evidenceIds.length} evidence file(s).</p>}</>}</section>}
  <h2>Reporting queue</h2><p>Each issued document under a reporting-required profile carries one immutable signed payload per version. An unknown outcome is reconciled by status query before any resend; an envelope rejection is repaired as a new payload version; a financial rejection needs a correction document.</p>
  {queue.items===null?<Loading/>:table(['Document','State','Deadline','Attempts','Remote id','Rejection','Actions'],queue.items.map(t=>[link('/sales/invoices/'+t.documentId,t.officialNumber||t.documentId.slice(0,8)),t.state.replace('_',' '),t.deadlineAt?when(t.deadlineAt):'—',t.attemptCount,t.remoteId||'—',t.rejectionClass?(t.rejectionClass==='financial'?'Financial: issue a correction document':'Envelope: repair and retry')+' — '+t.rejectionReason:t.reason||'—',<div key="a" className="action-row">{['unknown','sending','queued','retry_wait'].includes(t.state)&&tact(t,'Reconcile status','reconcile','transmission.reconcile')}{(t.state==='retry_wait'||(t.state==='rejected'&&t.rejectionClass==='envelope'))&&tact(t,'Retry','retry','transmission.retry')}</div>]),'Nothing queued for reporting.')}
  {can('registration.prepare')&&bookId&&<section className="demo-card"><h2>Registration pack</h2><p>Assembles the entity, branches, approved bank accounts, the active regulatory profile and the evidence manifest as a restricted pack. The pack is an application aid; the authority's permit is recorded separately from its own decision evidence.</p><Editor id={'regpack'+entityId} label="Generate pack" onSave={async d=>{setError(null);try{const r=await api('POST','/registration-packs',{entityId,key:uuid(),body:{reportType:d.authority,bookId,periodStart:d.periodStart,periodEnd:d.periodEnd,asOf:new Date().toISOString(),format:'json'}});setJob(r.data);return true;}catch(e){setError(asError(e));return false;}}}>{input('Authority','authority','BIR','text',{required:true})}{input('Scope from','periodStart',today().slice(0,4)+'-01-01','date',{required:true})}{input('Scope to','periodEnd',today().slice(0,4)+'-12-31','date',{required:true})}</Editor>{job&&<p role="status" aria-live="polite">Pack job {job.state.replace('_',' ')}{job.state==='succeeded'&&job.resultResourceId&&<> · {link('/evidence/'+job.resultResourceId,'open the pack')}</>}</p>}</section>}
 </>;
}
