from pathlib import Path
import json,re,hashlib
R=Path('D:/DCP/LARA'); O=R/'docs/development'; (O/'phases').mkdir(parents=True,exist_ok=True); (O/'contracts').mkdir(exist_ok=True)

P={
2:dict(title='Finance workspace',deps='P01',scope='A production work and evidence workspace with organization setup, parties, access, approvals, tasks and obligations. No financial posting is enabled yet.',
flow='Organization draft → validate → independently approve activation; invite user → accept OIDC invitation → scoped membership. Party draft → identity/evidence checks → active. Upload → quarantine → scan → available. Task open → assigned/in_progress → resolved, or waiting_for_information with owner and due date retained.',
data='Use organization/security tables in the shared data contract. Add settings_versions(entity_id,kind,version,payload_hash,approved_by,effective_at), delegation(principal_id,delegate_id,permission_scope,valid_from,valid_to,approved_by), and onboarding_checks(entity_id,check_code,status,evidence_id). Membership changes increment revocation version. No cross-entity bank-account or branch FK.',
rules='Setup requires legal name, base currency PHP, fiscal-year start, timezone, at least one branch and an independent controller. Tax/permit fields may remain pending while only workspace capability is active. Validate identity applicability without filling fake TINs. Party merge is a reviewed alias/link operation, never destructive replacement of posted snapshots. One identity can have roles but AR/AP balances never net automatically. Obligations instantiate from versioned templates; changes preserve prior completion evidence.',
ui='Settings setup wizard with resume; company/branch/party lists and detail; membership and approval policy screens; My work with filtered owner/due/status views; evidence preview and comments; obligation calendar. Audit view shows actor, action, time and evidence. Display missing activation blockers next to each capability.',
tests=['Create a second tenant and prove all API/search/evidence/count surfaces isolated (CORE-08).','Change a membership and deny an already queued export after revocation (CORE-14).','Approve an unchanged settings version using another principal; material change invalidates it.','Resolve a missing-evidence task and update related checks without duplicate tasks.','Upload mismatched checksum, executable disguised as PDF and infected fixture; none becomes available.'],
migration='Create tenant-owned tables, composite scoped FKs, RLS and immutable audit. Seed only permission definitions and role templates; no live tenant/party/rule data. Existing demo data remains in its own database.',
activation='Workspace owner accepts roles, object-storage scanning, retention policy and audit export. Financial capabilities remain disabled. Rollback disables workspace writes but preserves evidence/read access.'),
3:dict(title='General ledger and close',deps='P02',scope='Production PHP management books with manual journals, controlled source imports, periods, report snapshots and a complete supported close. No sales/AP control subledgers are falsely claimed before their modules.',
flow='Draft journal → submit → independent approval → post. Original → reversal request → approval → new reversing entry. Period open → soft_closed → required reconciliation/substantiation complete → locked. Reopen, if allowed, creates a new close version and reports; old snapshot remains.',
data='Shared ledger tables plus account_dimension_rules(account_id,dimension_type,required), substantiations(period_id,account_id,preparer,reviewer,evidence_id,state), statement_mappings(account_id,statement,line_code,version), journal_templates(code,lines,effective_from), and source_control_balances(batch_id,control_account_id,detail_total). Import staged rows contain source key, account/date/debit/credit/branch/dimensions and evidence.',
rules='Enforce shared PostingService algorithm, not UI-only checks. Require leaf active account and mandatory dimensions. Openings must tie detail to control accounts, including AR/AP if imported from retained sources. Reject overlapping opening loads. Trial balance sums posted functional lines by approved date/cutoff. Balance sheet follows account category/mapping; income statement sums revenue/expense; retained earnings close transfers income/expense balances exactly once per fiscal year and records links. Basic report labels are management statements until applicable presentation/disclosures are approved. Manual schedule imports support accruals/depreciation; no hidden asset engine.',
ui='Chart tree with cycle prevention; journal editor with running debit/credit difference and source preview; import staging/errors; general journal/ledger drill-down; trial balance/basic statements; close checklist and account support view; correction preview. Lock/adjustment actions show impact and reasons.',
tests=['Execute balanced/unbalanced, period-race, immutable-write and retry cases CORE-01–09.','Import openings twice; second command returns prior result; changed source hash conflicts.','Trial balance and statements reconcile to lines before/after reversal; original report checksum unchanged.','Attempt control-account manual journal and posting to frozen/inactive/nonleaf account; reject.','Close year twice; one retained-earnings effect; new-year opening and prior-year snapshot consistent.'],
migration='Add ledger/document/period tables and mandatory deferred balance enforcement. Existing P02 data preserved. Backfill no financial records automatically; create books/accounts through approved setup. Test old app compatibility during migration.',
activation='Controller signs account mapping, openings, source ownership and close rehearsal. This is a scoped ledger capability; statutory CAS replacement requires P07 and all customer dependencies. Disable new posting for rollback; use forward correction for committed entries.'),
4:dict(title='Sales invoicing and receivables',deps='P03',scope='Complete service invoicing and collections for the enabled PHP tax profile, including advances, credits, aging and delivery evidence. Tax computation kernel ships here as a dependency; official reporting-required profiles stay blocked until P07.',
flow='Direct invoice or approved quotation/order → draft → validate → submit/approve where policy requires → issue/post once → deliver → allocate receipts → settled. Quote/order conversion uses immutable source link and remaining billable quantity/value. Credit references original and reverses only eligible amounts. Customer advance is separately posted and later applied.',
data='documents/lines/relations, series/number_events, open_items, settlements/allocations, tax_rule_versions/events, plus payment_terms(id,installments_json), credit_limits(party_id,currency,limit,policy_version), deliveries(document_id,recipient_hash,template_version,state,provider_reference), party_snapshot(document_id,immutable_json). Tax fields are server-computed snapshots. Due schedule stores amount/date per installment; sum equals receivable.',
rules='Tax kernel supports percentage-of-approved-base VAT/zero/exempt and withholding classification through approved versioned profiles. For exclusive price: line net = round(quantity×unit_price−discount, currency scale); tax = round(net×rate, scale); gross=net+tax. Inclusive price: gross=round(quantity×unit_price−discount); net=round(gross/(1+rate)); tax=gross−net. Mixed lines summed, never classify by header alone. Profile selects line or document rounding; document method allocates residual by largest fractional remainder then line number. No live profile without signed examples. Credit limit uses open posted AR plus reserved approved orders; override independently approved. Apply payments with ordered locks, no negative outstanding. Reprints preserve number and snapshot. Buyer delivery does not imply reporting acceptance.',
ui='Invoice list/editor/timeline, optional quotations/orders, customer aging and statement, credit preview, advances and allocation workbench. Four statuses always separate. Payment links, recurring subscriptions, statutory discounts and portals are later disabled capabilities.',
tests=['AC-01/02/05/06 exact postings and open balances; input totals cannot override server tax.','Concurrent issuance yields unique numbers; crash/retry allocates once and explains unused numbers.','Credit more than eligible original or allocate same receipt twice fails.','Mixed inclusive/exclusive lines follow profile golden rounding cases, including 0.01 residual.','Reporting-required customer attempts activation before P07; blocked despite working invoice demo.'],
migration='Add sales/tax kernel tables and approved profile registry with draft-only reference fixtures. Never activate sample rates in a live tenant. Backfill existing parties with customer role only through explicit onboarding.',
activation='Advisor/controller approves invoice profile, templates, series, tax examples and customer eligibility; required external authorizations and reporting adapter must exist. Delivery adapter qualified. Rollback halts new issuance but keeps copies/corrections/evidence available.'),
5:dict(title='Purchasing payables and expenses',deps='P04',scope='Complete PO/non-PO services purchasing, bills, supplier credits, advances, expense claims, withholding records and authorized manual payment settlement. Three-way stock matching waits for P10; bank-file automation waits for P06.',
flow='Optional purchase request → approval → PO; bill direct or PO-linked → duplicate/evidence/tax validation → approve → post. Payment proposal → independent authority → record real manual release with evidence → settlement. Employee advance → liquidation lines → return/reimburse difference. Supplier credit/advance application uses linked accounting.',
data='purchase_orders/lines with ordered/received/invoiced amounts, receipts_of_service(order_id,evidence_id,accepted_by), bills as documents, withholding events/certificates, payment_orders/settlements, expense_claims(employee_party_id,advance_id?,policy_version,state), expense_lines(claim_id,expense_date,account_id,tax_rule_id,evidence_id,amount), and beneficiary_versions.',
rules='Duplicate key: entity + supplier + normalized supplier invoice reference + approved identity context; retain original reference. Exact duplicate blocks; fuzzy amount/date similarity warns with reviewer disposition. Policy decides PO and receipt-of-service requirements. Withholding timing is profile-selected accrual/payment; tax_events prevent repeated recognition. Payment proposal uses payable residual after recognized withholding/credits and separate approval from bill. Beneficiary change invalidates payment authority. Manual released and settled states need independent evidence; no screen action sends bank money. Advance liquidation posts expense/tax against advance, with remainder refund/payable. Certificates derive from tax events and store reviewed output version.',
ui='Bill source/draft review; request/PO list; two-way match differences; supplier aging; payment authority/release evidence; employee claims and unliquidated advances; withholding certificate preview. No dummy PO for utility bills.',
tests=['AC-03/04 tie expense/input tax/AP/withholding and ensure payment does not repeat tax.','Payment-time profile recognizes withholding once at settlement instead.','Supplier reference with case/spacing/punctuation normalization is detected; legitimate distinct reference can proceed.','Change beneficiary after approval and reject release; repeated manual settlement yields one effect.','Liquidate partial advance then return remainder; balances and evidence reconcile.'],
migration='Introduce purchasing/claims/payment tables with explicit settlement effects. Separate beneficiary encrypted history and reviewed version. Existing customer-only parties can gain supplier role without merging balances.',
activation='Finance signs PO/non-PO policy, withholding profiles, manual payment responsibility and certificate obligations. If required certificate/form output is not available until P07, retain supported external preparation with signed reconciliation boundary or block that customer. Never call unsupported tax workflow complete.'),
6:dict(title='Treasury cash and bank reconciliation',deps='P05',scope='Complete supported-bank CSV reconciliation, manual transfer controls, checks/PDCs, cash count/handover, payment-file generation and explicit settlement confirmation. No direct bank execution is implied by file export.',
flow='Statement upload → validate totals/duplicates → stage → propose matches → reviewer confirms → reconciled snapshot. Payment authorize → generate locked bank file → release evidence/unknown → settle/return. PDC receive/issue → custody/release → present/deposit → clear or dishonor → linked replacement.',
data='Shared bank/check/reconciliation tables plus bank_file_runs(bank_account_id,format_version,hash,state,export_evidence), bank_file_items(run_id,payment_id,amount), cash_sessions(branch_id,cashier,opened_at,closed_at,expected,counted,variance,state), cash_count_lines(session_id,denomination,quantity), transfers(from_account,to_account,currency,amount,state), and handovers(session_id,outgoing,incoming,attestations).',
rules='CSV contract: source_line_key, booked_date YYYY-MM-DD, value_date optional, signed_amount decimal (credit to bank positive), currency, reference, description. Batch supplies opening/closing balances; opening + lines = closing. Duplicate line keys across imports do not repost. Match candidate hierarchy exact reference/currency/amount, then deterministic date/amount suggestions; never silently confirm ambiguous matches. Partial/grouped matches conserve amounts. Fees/exchange differences require approved journal, not tolerance write-off. Transfers post both sides in one command or a documented clearing path. PDC receipt is custody only until approved recognition event; default collection accounting at clearing, with no available-cash inflation. Bounce reverses only recorded settlement. Cash variance requires reason and approved expense/receivable policy, never overwrite counted value.',
ui='Bank import preview, side-by-side matching, split/group allocations, difference breakdown; payment runs; check register and release calendar; cashier close with denominations, deposits, handover signatures and unresolved variance. Export file displays generated versus bank-accepted versus settled.',
tests=['AC-07 and CORE-10/12; ambiguous match remains unconfirmed.','Statement opening + lines differs from closing: reject completion.','Repeat payment file generation/release with same key and get one run/effect.','Bounced partial PDC preserves unrelated allocations and creates linked reversal.','Cashier cannot certify own required independent handover; variance remains visible.'],
migration='Add treasury tables; convert P05 manual payments to references without rewriting prior journal lines. Start bank reconciliation from signed opening statement cutoff; historical matched status cannot be fabricated.',
activation='Qualify one actual pilot bank format/check layout with bank/customer acceptance, signer matrix and outbound custody controls. Direct bank API remains disabled unless separately contracted and tested. On rollback stop new release files, reconcile all released/unknown effects first.'),
7:dict(title='Tax compliance and e invoicing',deps='P06',scope='Complete enabled taxpayer-profile return preparation, books, filing evidence, registration evidence and durable e-invoice reporting. Every form and adapter is enabled individually only with its authoritative version and test evidence.',
flow='Select period/profile → freeze reconciled source cutoff → compute deterministic tax events/return lines → resolve exceptions → independent approval → export → record external filing/payment acknowledgement. Invoice event → build immutable payload → validate/sign → send → accepted/rejected/unknown → reconcile. Registration checklist → evidence pack → actual external decision recorded separately.',
data='return_runs/lines(line_code,basis,amount,source_query_version), return_source_links(run_id,tax_event_id), filing_records(run_id,external_reference,filed_at,evidence_id), regulatory_profiles(jurisdiction,coverage,version,source_hash,approved_by), schema_artifacts(profile_id,type,version,hash,evidence_id), transmission jobs/attempts and registration_cases(authority,status,scope,evidence).',
rules='Supported form registry includes 2550Q/SLSP, 0619-E/1601-EQ/QAP, 1601-FQ/2306 where applicable, 2307/SAWT, 1604-E, payroll-import 2316 and annual income-tax/eAFS preparation as independently enabled outputs. Exact official field widths/codes/schema are imported as reviewed artifacts, not guessed in this spec. For each output store mapping from tax event/account to field, filter basis/date, rounding, validation, totals and authority evidence. No missing mapping may produce a plausible zero. One click books/export uses immutable report snapshot and manifest. EInvoiceTransport contract handles key custody, deadline profile, unknown acknowledgement, signed payload and correction rules. No blanket three-day/PTI/QR claim. Already issued financial data stays immutable; a transport-only re-encoding has versioned hash and reason.',
ui='Compliance workbench, readiness with failed/not-tested states, return-to-ledger drill-down, certificate matrix, registration pack, filing/payment evidence, reporting queue with deadline and accountable owner. Plain-language rejection view distinguishes financial correction from envelope repair.',
tests=['Every enabled form has golden accepted fixture plus each validation-failure class.','Return/source/ledger totals tie and replay of old cutoff/profile produces same hash.','Kill worker after remote acceptance; recover via status query without duplicate submission.','Unsigned/unapproved payload, wrong taxpayer credentials and expired profile are blocked.','Generated pack cannot mark actual permit or filing as complete; evidence required.'],
migration='Add compliance tables/adapter metadata; no live credentials or certified schemas in seed. Backfill existing issued documents into reporting queue only after signed applicability/cutoff plan to prevent historic double reporting.',
activation='Tax lead approves current official schema/form artifacts, taxpayer coverage, correction/retention profiles and golden cases. Provider/taxpayer sandbox/certification and credentials are required. This is an explicit external activation gate; working fixtures alone are insufficient. Rollback pauses transmission, preserves queue and reconciles remote status.'),
8:dict(title='Financial institution coexistence',deps='P07',scope='A specific signed bank/FI pilot with canonical source journal and balance feeds, account mappings, branch roll-up and applicable GRT/final withholding/DST. Core banking, valuation, lending and ECL calculations remain in named authoritative systems.',
flow='Source file/API batch → authenticate/checksum/control totals → stage rows → mapping validation → approve → post once → reconcile source balances and tax events → branch/entity close. Missing source batch creates blocking task. Corrected source batch is a linked reversal/replacement, not overwrite.',
data='source_systems(code,owner,granularity,cutoff_timezone), source_ownership, source_batches/rows, mapping_versions(source_account,target_account,dimensions,tax_profile), expected_batches(source,period,deadline), source_balance_snapshots(account,currency,balance,cutoff), tax_instrument_facts(instrument_ref,type,maturity,amount,income_category,event_date), and branch_rollups with reconciliation manifests.',
rules='Canonical journal feed columns: external_batch_id, external_line_id, accounting_date, book_code, branch_code, account_code, currency, debit, credit, source_document_ref, dimensions, tax_event_ref optional. Manifest includes count, debit/credit totals, currency totals and SHA-256. Reject partial commit of a declared atomic batch. Summarized posting requires durable underlying detail reference and control totals. Tax profiles classify bank income/instrument facts through reviewed effective rules; no inferred universal VAT/GRT treatment. Due-to/due-from interbranch pairs reconcile, with asymmetric batch timing visible. Separate currencies/FCDU/trust required by pilot block activation until P09 or remain completely outside LARA ownership with verified interfaces.',
ui='Source ownership matrix; batch monitor/error workbench; mapping diff preview; branch reconciliation and missing-feed dashboard; institution tax worksheet with instrument/source drill-through; read-only examiner scope.',
tests=['Duplicate batch 100 times yields one journal; same ID changed checksum conflicts.','Missing or late batch blocks affected close, not unrelated entity.','Source detail/control totals mismatch cannot be approved silently.','Interbranch pair appears in branch books and cancels in entity roll-up without cross-entity consolidation.','Each enabled GRT/DST/final withholding rule has advisor-signed boundary-date/maturity golden cases.'],
migration='Add canonical feed and rule fact tables; require effective source ownership before ingestion. Transition from manual imports at documented cutoff; detect duplicate source ranges across both routes.',
activation='Named design partner signs entity/books/currency/tax/feed matrix and representative parallel month. Required FX/separate-book obligations pull in P09. Reuse bank adapters only after measured volume/recovery tests. No universal-bank replacement claim. Rollback stops source acceptance at a durable watermark and reconciles any in-flight batch.'),
9:dict(title='Multiple currencies and separate books',deps='P08',scope='Transaction/functional currency accounting with controlled rates, realized/unrealized FX and separately permissioned book partitions, including approved RBU/FCDU/trust source boundaries. It does not implement investment/loan/trust instrument engines.',
flow='Approve rate version → enter foreign-currency document → snapshot conversion → post both amounts → settle at approved rate → post realized FX. Period-end revaluation preview → approve → post once → optional next-period reversal. Separate books → reconciled management combination, distinct from group consolidation.',
data='fx_rates, currency_metadata(code,minor_units), revaluation_runs(book_id,period,rate_set,method,state,entry_ids), fx_open_item_layers(open_item_id,txn_remaining,func_carrying), book_links(source_book,target_view,translation_policy), and book_access. Each journal records one transaction currency and one functional currency; translated adjustments use functional amounts with explicit purpose.',
rules='Store original functional carrying value and remaining transaction currency per open item. Partial settlement consumes proportional carrying value with final allocation absorbing rounding. Realized gain/loss is functional cash equivalent minus consumed carrying value with sign by AR/AP direction. Revalue eligible monetary open balances at approved closing rate; difference posts to unrealized FX account, tied to rate set and prior carrying amount. Never revalue all asset/equity accounts blindly. Missing rate blocks, not defaults to 1. Functional-currency change is a separately reviewed migration, not a settings edit. Trust and institutional books cannot mix postings; combined management view labels basis and exclusions.',
ui='Rate import/review; transaction and functional side-by-side values; revaluation preview/difference; book selector and access; source/account reconciliation per book.',
tests=['AC-10 and partial settlement leave exact remaining foreign/functional balances.','Run same revaluation twice and get one effect; new rate set requires linked adjustment.','Unavailable rate, inverted pair mistake and unauthorized book access rejected.','Reversal retains original rate and amounts; not recalculated at today’s rate.','RBU/FCDU/trust partitions reconcile independently and combined view does not double count.'],
migration='Backfill original P03–P08 entries with transaction=functional PHP and rate=1 reference; never change posted values. Add FX fields/constraints additively; verify totals before enabling non-PHP.',
activation='Controller approves monetary-account classification, FX sources, functional currencies, book boundaries and tax/report interactions. Required separate-book reports tested. Rollback disables new FX activity but retains native-currency history/report access.'),
10:dict(title='Inventory costing and three way matching',deps='P06; P09 for FX items',scope='Perpetual inventory for supported trading goods: warehouses, receipts/issues/transfers, valuation, count, batch/serial and landed cost with complete stock-to-ledger reconciliation.',
flow='PO → receive goods → value receipt → match supplier invoice/receipt/PO → approved variance → post. Issue/sale consumes valuation layers; transfer preserves value. Count freeze/cutoff → observed quantity → review variance → adjustment. Landed cost allocates approved charges to receipts and remaining/sold quantities.',
data='items(sku,uom,stock_account,cogs_account,cost_method,tracking), warehouses(code,branch), stock_movements(item,warehouse,type,qty,date,source_doc), valuation_layers(receipt_id,qty_remaining,unit_cost,currency), stock_allocations(issue_id,layer_id,qty,cost), count_sessions/lines(expected,observed), lot_serials, landed_cost_runs(method,charge,allocations), and goods_receipts/lines.',
rules='Item/entity cost method FIFO or moving weighted average, selected before first movement. No negative stock in initial production profile. FIFO consumes oldest received layer ordered effective date then immutable receipt ID; weighted average recalculates after each receipt including approved costs, with residual carried to final issue. Lock item/warehouse aggregates in sorted order. Backdated movements before a closed inventory period blocked; open-period backdating requires deterministic recost preview and linked adjustment for affected issues, not silent rewriting. Transfer conserves quantity/value and recognizes no profit. Count variance posts stock gain/loss with independent approval. Landed cost allocate by value/quantity/weight approved method; round residual deterministically; sold portion to COGS, remaining to inventory. Three-way tolerances never waive missing mandated receipt evidence.',
ui='Stock card, movement and valuation layers; receipt/matching workbench; count entry/review; landed-cost preview; inventory book and year-end export; stock/GL differences with source links.',
tests=['AC-09 plus two-layer FIFO, weighted average and partial return cases.','Concurrent issues cannot consume same stock or produce negative quantity.','Transfer total value conserved; serial cannot exist in two warehouses.','Count/landed cost journals reconcile to valuation and control account exactly.','Backdated open-period receipt triggers approved recost; locked period rejects.'],
migration='Opening stock import requires quantity/value per item/location and reconciled GL opening; source inventory ownership transfers at cutoff. Cost method changes after activity are blocked absent a separately reviewed conversion.',
activation='Controller signs costing method, unit conversions, cutoff, negative-stock policy and opening count. Goods profiles cannot be enabled until stock/GL/AR/AP and applicable inventory outputs pass. Rollback stops movements, not valuation evidence.'),
11:dict(title='Assets recurring work and recognition schedules',deps='P03/P05; P09 for FX',scope='Asset register/lifecycle and deterministic schedules for depreciation, prepayments, deferred revenue, recurring draft invoices/journals and employee deductions. Distinct accounting semantics share execution infrastructure.',
flow='Capitalization draft from bill/CIP → approve asset and in-service date → schedule preview → approve → monthly execution → reconcile. Transfer/split/merge/disposal/impairment creates approved linked event. Schedule modification creates prospective version; prior postings remain immutable.',
data='assets(tag,class,cost,residual,useful_life_months,in_service_date,location,custodian,status), asset_components(parent_id,cost,life), asset_events(kind,effective_date,amount,source), recognition_schedules(kind,basis,start,end,method,policy_version,state), schedule_lines(period,amount,account_mapping,posted_entry_id), schedule_versions, and book_tax_layers(asset,book_value,tax_value,rule_version).',
rules='Initial depreciation convention monthly from in-service month, no partial-month proration unless approved policy explicitly selects daily actual/actual. Straight-line amount=(cost−residual)/months, rounded each period with final residual adjustment. Declining balance applies approved rate to opening carrying amount, floored at residual; sum-of-years uses approved annual weights then documented monthly allocation. Useful life/method changes prospective from approved effective period, no rewrite. Disposal removes cost/accumulated depreciation and recognizes proceeds difference. Split/merge conserves total gross cost and accumulated depreciation. CIP depreciates only after in-service transfer. Prepayment/deferred revenue schedules allocate recognition over approved service periods. Jobs create drafts or use approved deterministic schedule authority; AI never posts. Unique schedule/version/period prevents rerun duplicates.',
ui='Asset register/detail, schedule preview, depreciation run/review, capitalization/CIP, disposal calculation, book/tax comparison; recurring work calendar and failed period tasks.',
tests=['AC-08 plus residual/final-month, method-change and leap-year daily policy cases.','Duplicate schedule run posts once and locked period creates task instead of bypass.','Split/merge cost and depreciation conserved; disposal gain/loss correct.','Deferred revenue schedule total equals contract amount with final rounding residue.','Book/tax schedule versions reconcile independently and changes are reproducible.'],
migration='Import reconciled cost/accumulated depreciation/remaining-life per asset and disable overlapping retained-source schedule ownership. No automatic catch-up posting during migration.',
activation='Controller approves asset classes, recognition methods, opening register, impairment/revaluation journals and disclosure/report boundary. Scheduled posting authority is explicit and revocable; all generated entries remain traceable. Rollback pauses scheduler and reconciles its last committed period.'),
12:dict(title='Evidence backed AI assistance',deps='P07; enabled target modules',scope='Optional capture/coding/matching suggestions, exception explanations, finance questions, close/audit drafts and local document readers with measurable quality. Deterministic controls remain authoritative.',
flow='Authorized evidence selection → provider policy/masking → model request with constrained tool schema → validated suggestion or abstain → source-linked review → named user accepts/edits/rejects → normal domain command. No tool directly approves/posts/sends/files/pays.',
data='ai_runs(feature,model_version,prompt_version,tool_schema_version,input_refs,scope,started/completed,cost,status), ai_suggestions(run_id,fields_json,source_spans,uncertainty,review_decision,reviewer), evaluation_sets(id,version,hash,consent_basis), evaluation_results(metrics,failures), and model_feature_configs(tenant,feature,enabled,budget,provider_policy). Store only minimized input/output per approved retention policy.',
rules='Allowlist tools: read permitted source, read canonical report, propose draft fields, propose task/comment and explain deterministic finding. Deny arbitrary SQL, filesystem, arbitrary URLs and outbound communication. Numeric answers come from canonical reports with entity/book/period/currency/as-of and source links; model prose cannot replace calculated values. Uploaded text is data, not instruction. Coding learns only through reviewed tenant-specific mappings; no shared training without explicit approval. Missing/poor-quality evidence causes abstain or field uncertainty. Evaluate at least 200 held-out local bills including handwriting and poor scans before enabling those readers; require Finance-approved material-field error thresholds, zero unauthorized actions and no control bypass. Match suggestions never auto-reconcile ambiguous lines.',
ui='Source/draft split view, per-field evidence and uncertain marker; review all material tax/payee/amount fields; ask-your-books with scope banner; run history and explain/accept/edit/reject; feature opt-out. Registration/audit packs show evidence gaps and cannot sign attestations.',
tests=['Document prompt injection cannot change tool authority, leak tenants or send messages.','Canonical finance questions return exact report totals; unsupported questions abstain.','Provider timeout/budget exceeded leaves manual work fully usable.','Model/prompt update failing held-out metrics cannot activate.','Actor revoked during run cannot retrieve result or execute suggested action.'],
migration='No vectors/shared training required for first release. Add AI run/suggestion tables and explicit per-feature opt-in. Existing deterministic controls unchanged; migrations never infer approved training consent.',
activation='Privacy/security approves provider region/retention/training terms; Finance accepts evaluation threshold and results; Product measures review time versus baseline. No invented confidence threshold from model self-rating. Rollback feature/model version only, not accounting records.'),
13:dict(title='Customer supplier portals and messaging',deps='P04–P07',scope='Authenticated customer/supplier self-service for their own invoices, statements, bill submissions and certificate requests; one qualified messaging channel and payment-link provider with reconciled status.',
flow='Scoped invite → identity verification → portal membership → view authorized records/upload evidence → finance review. Outbound request draft → authorized send → delivery evidence. Payment link → provider event validation → reconcile → normal settlement command, not immediate trust in browser return.',
data='portal_memberships(principal,party_id,entity,role,expiry,status), share_grants(resource,recipient,expires,scope), message_requests(template,recipient,source,approval,state), delivery_receipts, provider_payment_intents(document,amount,currency,key,status), webhook_receipts(provider,event_id,hash,signature_state).',
rules='Portal membership scope is party + entity and allowed resource kinds; one email at two companies confers no cross-access. Uploads use quarantine and cannot become posted bills automatically. Verification page reveals minimal approved fields with opaque identifiers; no public TIN/address/full document. Authenticate webhook signature/timestamp, dedupe event, verify amount/currency/payee and reconcile server-to-server before settlement. Email/chat content minimizes sensitive data and links into authenticated review; permissions are rechecked on opening. Send requires explicit actor authorization; AI chaser only drafts. Revocation stops future hosted access, not copies already downloaded.',
ui='Portal invoice/statement and certificate inbox, supplier submission status, secure request history; internal communication timeline and failed-delivery task. Clearly distinguish customer-paid claim from provider-settled receipt.',
tests=['Portal user enumerates another party record and receives no data.','Forged/replayed/out-of-order payment webhook never double settles.','Expired invite/share token cannot expose evidence.','Supplier upload missing legal fields routes to review, not posting.','Message provider failure retries without duplicate authorized send.'],
migration='Introduce scoped external identities separately from internal memberships; never infer portal access from party email. Historical links must be newly authorized, not publicly backfilled.',
activation='Qualify one chosen channel/payment provider, consent/notification policy, terms and support. Without provider evidence, portal-only release may ship with those capabilities disabled; do not mark the provider feature complete. Rollback revokes grants and pauses sends.'),
14:dict(title='Accounting firm multi client workspace',deps='P07/P13',scope='Firm users can operate explicitly delegated client scopes through one login, with assignments, deadlines and readiness views. Client books and permissions remain isolated.',
flow='Firm organization → client invitation/delegation → authorized staff assignment → explicit client context → task/action → client audit record. Revoke client mandate → invalidate staff/session/jobs and hide aggregates.',
data='firms(name,owner), firm_staff(principal,role,status), client_mandates(firm,tenant,entity,permissions,valid_from/to,approver,state), client_assignments(mandate,staff,scope), aggregate_snapshots(firm,actor,scope_hash,as_of,counts). Cross-tenant references live in a restricted authorization service, not unrestricted financial joins.',
rules='Firm identity does not automatically access clients. Resolve each mandate then execute client-scoped queries; aggregate only permitted counts/amounts and label currency/entity. No client financial data in global caches without scope/revocation keys. Bulk operation fan-out creates separate per-client commands and approvals; no implicit cross-company posting. Maker-checker applies within each client, including firm staff. Billing/commercial firm plan is configurable metadata, not accounting authorization.',
ui='Client switcher with persistent context; assigned-client list; deadline/exception roll-up; staff assignment and mandate evidence; client-scoped deep links. Never show combined unlabeled monetary totals across currencies.',
tests=['Remove one mandate and immediately invalidate cached counts/exports for that client.','User assigned client A only cannot search/client-switch to B.','Bulk reminder/action produces independent per-client outcomes without data leakage.','Same user maker/approver through firm and direct membership remains prohibited.','Different currency aggregates remain separated and traceable.'],
migration='Add firm authorization records; existing tenant memberships unchanged until client accepts a mandate. No automatic affiliation inferred from domains/emails.',
activation='Each client signs permission/expiry boundaries; security adversarial tests cover counts and cross-client jobs. Rollback disables aggregation but preserves each valid direct client scope.'),
15:dict(title='Intercompany and consolidation',deps='P09/P11',scope='Group reporting from approved entity snapshots, paired intercompany transactions, eliminations and translation. Consolidation creates a separate reporting book, never rewrites subsidiary ledgers.',
flow='Define group ownership/reporting currency → approve entity mappings → paired intercompany drafts accepted per entity → post in each entity with tracked pair state → freeze entity closes → translate → propose eliminations → review → consolidated snapshot.',
data='groups(reporting_currency), group_members(entity,ownership_pct,effective_dates,method), group_account_mappings, intercompany_pairs(source_doc,target_doc,state,shared_reference), consolidation_runs(period,member_snapshot_ids,rate_set,state), elimination_entries(run_id,accounts,amount,reason,evidence), translation_adjustments(run_id,source,policy,amount).',
rules='Cross-entity commands are a saga with separately authorized local transactions; no claim of atomic remote approval. Pair stays pending/exception until both sides reconcile; failed second side never silently rolls back issued first side. Full consolidation for controlled wholly-owned pilot entities first; partial ownership/equity-method requires an explicit approved extension before activation. Translate balance sheet at closing rates and income/expenses under approved period-average or transaction-rate policy; opening equity/historical reserves and translation reserve preserve approved basis. Never sum mixed currencies directly. Eliminations tie counterparties/references and show unresolved differences; no blanket elimination to force balance.',
ui='Group setup and mapping; pair exceptions; member-close readiness; translation/rate preview; elimination worksheet; consolidated statements with member/elimination drill-down.',
tests=['Two-entity balanced fixture consolidates and eliminates reciprocal AR/AP and revenue/expense once.','Missing second-side approval remains exception; no fabricated journal.','FX translation difference recorded in approved reserve account with traceable rate.','Rerun same member snapshots yields same result/hash; new snapshot creates new version.','Group reviewer cannot mutate subsidiary books without separate entity authority.'],
migration='Create group reporting schema and scoped permissions, retain entity keys. Existing interbranch roll-up is not converted to intercompany. No ownership assumptions for prior periods.',
activation='Controller approves ownership/method, mappings, rate policies and complete statement presentation. Unsupported minority/equity method blocks that member. Rollback leaves subsidiaries unchanged; supersede group snapshots.'),
16:dict(title='Budgets cost allocation and project accounting',deps='P10/P11',scope='Budget control, cost allocation, project revenue/cost views and progress/retention billing tied to normal documents. This is not a manufacturing or full construction scheduling system.',
flow='Budget version draft → review → activate; requisition/PO reserves commitment → bill consumes → cancellation releases. Allocation run previews source pools/drivers → approval → entries. Project contract → approved milestone/progress → billing with advance recoupment/retention → release retention when evidenced.',
data='budgets(period,version,currency,status), budget_lines(account,dimension,amount), commitments(source,amount,state), allocation_rules(source_filter,drivers,targets,effective_dates), allocation_runs(source_cutoff,rule_version,lines,entry_ids), projects(code,customer,contract_value,currency,status), milestones(project,amount,certified_value,evidence), retention_items(invoice,rate,held,released,due_condition), project_contract_versions.',
rules='Availability = approved budget − actual eligible spend − open commitments, with no double counting when a PO becomes a bill. Lock budget bucket during reservation; warn/block policy and authorized override retained. Allocation driver total must be positive; allocated rounded amounts sum exactly to source pool, residual to stable target ordering. Project billing cannot exceed approved certified/billable amount except reviewed change order. Retention separates due-now AR and retention receivable using approved account mapping; advance recoupment consumes documented advances, not revenue twice. Profitability uses posted cost/revenue with clear work-in-progress exclusions.',
ui='Budget vs actual/commitment drill-down; approval override; allocation preview/differences; project contract/milestones, progress billing and retention aging/release.',
tests=['Two simultaneous commitments cannot overspend blocking budget.','PO→bill conversion consumes commitment without double counting.','Allocation residual preserves exact pool and no duplicate rerun.','Progress invoice recoups advance/holds retention and release settles correct control account.','Change order version and approval visible; past billing unchanged.'],
migration='Initialize budgets and project openings through reviewed imports with no retroactive automatic reservations. Tag historical transactions only through approved reporting dimensions without modifying posted facts.',
activation='Finance approves budget basis, drivers, project accounting/retention profiles and contract evidence. Rollback stops new reservations/runs, reconciles existing commitments; posted project documents remain.'),
17:dict(title='Local operations feature releases',deps='P07/P09/P11/P16 as specified',scope='Independently shipped P17A leases, P17B statutory discounts, P17C marketplace/POS, P17D payroll remittance/import and P17E local obligations. Complete each enabled feature; the phase is not complete until its selected feature releases pass.',
flow='Each feature captures source once, validates profile/evidence, independently approves consequential effects, posts through shared services, reconciles and exports evidence. No separate posting engine or agent per industry.',
data='P17A lease_contracts(party,term_start/end,deposit,advance,escalation_json,withholding_profile), lease_events; P17B discount_eligibility(party,category,evidence,expiry) and discount_lines(document,basis,rate,exemption_profile); P17C payout_batches(channel,source_id,gross,fees,withholding,net), pos_closings(machine,shift,readings); P17D payroll_batches(source,period,counts,totals,hash), employee_tax_records(restricted), remittance_records(agency,period,amount,evidence); P17E local_obligations(authority,kind,property_ref?,due,amount,evidence).',
rules='P17A covers lessor billing, deposits, advances, escalation and approved tax treatment; deposits remain liabilities until approved application/refund. Lessee right-of-use/liability measurement requires an approved accounting profile and golden schedule before enabling that distinct feature; it is not inferred from recurring rent. P17B profile determines category/eligible goods/services/base/discount/exemption and required identity evidence; rates never hard-coded globally, no unauthorized ID exposure. P17C gross sales minus fees minus withholding/other explicit deductions equals payout; reconcile to imported sales to avoid reposting revenue. POS X/Z closure references unique machine/shift and match deposits. P17D imports payroll journals and required 2316/1601-C/SSS/PhilHealth/Pag-IBIG data with restricted permissions, reconciles source totals, does not calculate full payroll. P17E deadlines/amounts follow reviewed local authority profile; payment is standard AP/treasury evidence, not automatic government filing.',
ui='Feature-specific contract/eligibility/payout/payroll/import screens reuse document review, tasks, calendar and evidence; identity fields masked by role. Each feature displays its authoritative source and unsupported variants.',
tests=['P17A escalation boundary and deposit application do not recognize revenue twice; schedule sums correctly.','P17B eligible/ineligible, expired evidence and mixed lines follow approved golden cases.','P17C gross-to-net reconciliation explains every fee/tax; replay never duplicates sale/payout.','P17D payroll/employee tax totals tie and unauthorized user cannot view individual data.','P17E complete obligation requires payment/filing evidence applicable to that authority.'],
migration='Each feature has its own additive migration and entitlement, source mapping version and opening import. No catch-all JSON posting from external channels. Existing source-owner boundaries transferred only at signed cutoff.',
activation='Per-feature authority/provider/accounting examples and source formats reviewed before activation. Without these, existing product still ships; unsupported feature remains disabled and not marked done. Rollback pauses only affected adapter/scheduler and reconciles pending effects.'),
18:dict(title='Controlled extensibility and advanced assistance',deps='P12/P14–P17 as applicable',scope='Independently shipped P18A report authoring, P18B rule-change/impact proposals, P18C external draft tools and P18D versioned industry packs. Peer benchmarking and deferred government withholding are explicitly not activated by this phase.',
flow='Authorized builder selects allowlisted fields/metrics or draft tools → preview under current permissions → validate → reviewer publishes version → execute under caller scope → audit. Rule ingestion proposes changes/test cases; qualified human review and software release assessment precede activation.',
data='report_definitions(metric_ids,dimension_ids,filters,sort,version,state), custom_fields(resource_type,key,type,validation,visibility), tool_grants(client_id,allowed_tools,scope,expiry), rule_proposals(source_evidence,delta,impact_run,test_cases,state), pack_versions(manifest,dependencies,schemas,rule_refs,migrations,hash,state).',
rules='Report builder compiles an allowlisted query AST to parameterized queries; no raw SQL/JS, arbitrary joins or access to masked fields. Max query cost/row/time budget; async export uses scoped snapshot. Custom fields cannot replace statutory/accounting fields or bypass validation. Client tools may read authorized reports and propose drafts/tasks only; every request has scoped identity, request schema, idempotency and rate limits. No autonomous posting/approval/payments/filing/sending. Rule proposals show affected profiles/periods and cannot rewrite historical postings. Industry packs ship reviewed reusable configuration/code with dependency and upgrade tests, not customer forks. Tax computation comparisons use approved deterministic calculators and advisor review.',
ui='Report field/metric builder and saved report; rule source/diff/impact/review; tool client grant and revocation; pack install/upgrade preview with disabled unsupported dependencies.',
tests=['Query attempts unauthorized field/join or resource overrun and is rejected.','Client tool attempts approve/post/exfiltrate despite prompt injection and is denied.','Rule proposal cannot activate without independent review and passing test examples.','Pack upgrade preserves original data/profile snapshots and supports compatible rollback.','Multi-client custom report applies client mandate to each result and aggregate.'],
migration='Store definitions/grants/pack manifests; no runtime tenant scripting engine. Version query AST/schema and retain compiled report reproducibility. New field backfills are explicit reviewed jobs.',
activation='Security/Finance accepts tool and query allowlist, provider contracts and per-pack tests. Benchmarking requires a future separate privacy/cohort design and is not implementation-ready or promised here. Government withholding remains deferred by original scope decision. Rollback revokes tool grants and reverts definitions without changing financial facts.')
}

for n,p in P.items():
    phase=f'P{n:02}'
    txt=f'''# {phase} {p['title']}

**Depends on:** {p['deps']}. **Release:** complete supported module or explicitly enumerated feature release. **Baseline:** shared data/API/security specifications and RG-01–08 apply in full.

## Shipped scope

{p['scope']}

## User flow and states

{p['flow']}

## Data and migration contract

{p['data']}

All references use tenant/entity/book composite scope as applicable. Positive amount/quantity checks, unique source keys and enum checks are database-enforced. Archive referenced masters; retain immutable posted facts. Index owner/state/due queues and source/period lookups with tenant/entity leading columns.

## Calculation and business rules

{p['rules']}

## Screens and interaction

{p['ui']}

Every screen implements empty/loading/error/forbidden/stale-version/retry states and keyboard/mobile review behavior. No UI action bypasses API/domain rules. Output lists provide permitted CSV/PDF exports with scope, cutoff and checksum.

## Commands and service boundaries

Use the typed operations listed for {phase} in [OpenAPI](../contracts/openapi.json) and the shared command envelopes. Only the owning application service may execute transitions; side effects use outbox. Every financial effect calls PostingService inside the same transaction. Any additional endpoint needed to expose the specified screens must use the read/list and versioned-mutation conventions and be added to the reviewed OpenAPI before implementation; it may not invent a second payload/state model.

## Acceptance scenarios

'''
    txt+='\n'.join(f'- {phase}-T{i:02}: {s}' for i,s in enumerate(p['tests'],1))
    txt+=f'''

Also pass CORE-01–18 where applicable, previous-phase regressions, migration/restore/load checks for the new tables and the complete UI/API journey. The exact scoped BRD IDs are in [requirements.json](../contracts/requirements.json).

## Migration and recovery

{p['migration']}

## Activation and release

{p['activation']}

## Build order inside this phase

1. Add typed contracts, SQL migrations and permission/capability definitions.
2. Implement deterministic domain/state rules and transaction/repository tests.
3. Implement controllers, imports/jobs/provider adapter and idempotency/failure paths.
4. Implement complete UI journey, reports/evidence and accessible recovery states.
5. Run acceptance/regression/security/migration/recovery tests; record evidence and operator runbook.
6. Release the module with activation gates satisfied for each enabled customer profile. No later phase is reserved merely to harden this module.
'''
    (O/f'phases/{phase.lower()}-{re.sub("[^a-z0-9]+","-",p["title"].lower())}.md').write_text(txt,encoding='utf-8')

index='# Module implementation specifications\n\nEach phase inherits the shared data, API, security and release contracts. Prototype coverage is not production completion.\n\n'
for f in sorted((O/'phases').glob('p*.md')):index+=f'- [{f.read_text(encoding="utf-8").splitlines()[0][2:]}]({f.name})\n'
(O/'phases/README.md').write_text(index,encoding='utf-8')
(O/'contracts/phase-catalog.json').write_text(json.dumps({f'P{n:02}':{'title':p['title'],'dependencies':p['deps'],'spec':str(next((O/'phases').glob(f'p{n:02}-*.md')).relative_to(O))} for n,p in P.items()},indent=2),encoding='utf-8')
print('Wrote',len(P),'module specifications')
