from pathlib import Path
import json
R=Path('D:/DCP/LARA/docs/development');C=R/'contracts'
def save(n,o):(C/n).write_text(json.dumps(o,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
cat=json.loads((C/'phase-catalog.json').read_text())
deps={'P00':[],'P01':['P00'],'P02':['P01'],'P03':['P02'],'P04':['P03'],'P05':['P04'],'P06':['P05'],'P07':['P06'],'P08':['P07'],'P09':['P08'],'P10':['P06'],'P11':['P03','P05'],'P12':['P07'],'P13':['P04','P05','P06','P07'],'P14':['P07','P13'],'P15':['P09','P11'],'P16':['P10','P11'],'P17A':['P07','P11'],'P17B':['P04','P07'],'P17C':['P07','P10'],'P17D':['P07'],'P17E':['P05','P07'],'P18A':['P07','P12'],'P18B':['P12'],'P18C':['P12','P14'],'P18D':['P15','P16','P17A','P17B','P17C','P17D','P17E']}
titles={'P00':'Engineering baseline','P01':'UX prototype','P17A':'Lease billing','P17B':'Statutory discounts','P17C':'Marketplace and POS integration','P17D':'Payroll data and remittances','P17E':'Local obligations','P18A':'Report and custom-field authoring','P18B':'Rule impact and tax proposals','P18C':'Client draft tools','P18D':'Industry pack lifecycle'}
def spec(p):return {'P00':'03-phase-00-setup.md','P01':'04-phase-01-prototype.md'}.get(p,cat.get(p[:3],{}).get('spec'))
save('release-plan.json',{'version':1,'default_order':list(deps),'releases':[{'id':p,'title':titles.get(p,cat.get(p,{}).get('title')),'depends_on':d,'conditional_dependencies':['P09 for foreign-currency operation'] if p in ['P10','P11'] else ['every capability used by the selected pack/profile'] if p=='P18D' else [],'spec':spec(p),'release_gate':'RG-01..08','purpose':'engineering' if p=='P00' else 'synthetic_demo' if p=='P01' else 'production_scoped'} for p,d in deps.items()]})
back=json.loads((C/'backlog.json').read_text());tickets=[t for t in back['tickets'] if t['phase'] not in ['P17','P18']]
for t in tickets:
 if t['id'].endswith('-01'):
  t['depends_on_releases']=deps[t['phase']];t['depends_on']=[]
 else:t['depends_on_releases']=[]
req=json.loads((C/'requirements.json').read_text())['requirements']
for p in deps:
 if len(p)!=4:continue
 for i,(title,detail) in enumerate([('Contracts and schema','Typed commands, exact source mapping, scoped tables and permissions.'),('Domain behavior','Implement the feature calculation/state rules and invariants.'),('Adapters and jobs','Qualify real dependencies and implement retry/unknown-result handling.'),('Complete user flow','Screens, errors, evidence and output from beginning to completion.'),('Tests and recovery','Feature golden cases plus RG/security/migration/recovery evidence.'),('Release and activation','Tag independent feature release and activate eligible customer scope only.')],1):
  tickets.append({'id':f'{p}-{i:02}','phase':p,'title':titles[p]+' — '+title,'implementation':detail,'depends_on':[] if i==1 else [f'{p}-{i-1:02}'],'depends_on_releases':deps[p] if i==1 else [],'spec':spec(p),'requirements':[x['id'] for x in req if x['production_completion_phase']==p],'acceptance':p[:3]+' feature-specific tests in owning spec; RG-01..08','status':'specified_external_activation_gates_apply'})
back['tickets']=tickets;save('backlog.json',back)

uid=lambda n:f'00000000-0000-4000-8000-{n:012d}'
invoice={'kind':'invoice','branchId':uid(1),'bookId':uid(2),'partyId':uid(3),'documentDate':'2026-09-18','accountingDate':'2026-09-18','currency':'PHP','ruleProfileVersion':'DEMO-NOT-LEGAL-v1','lines':[{'description':'Synthetic service','quantity':'1','unitPrice':'10000.00','discount':'0.00','priceBasis':'exclusive','accountId':uid(4),'taxCodeId':uid(5),'dimensions':{}}],'evidenceIds':[]}
save('request-examples.json',{'examples':[{'schema':'DocumentCreate','name':'Synthetic invoice draft','value':invoice},{'schema':'JournalCreate','name':'Opening synthetic capital','value':{'bookId':uid(2),'accountingDate':'2026-09-01','documentDate':'2026-09-01','currency':'PHP','description':'Synthetic opening','lines':[{'accountId':uid(6),'branchId':uid(1),'debit':'100000.00','credit':'0','dimensions':{}},{'accountId':uid(7),'branchId':uid(1),'debit':'0','credit':'100000.00','dimensions':{}}],'evidenceIds':[]}},{'schema':'ApprovalDecision','name':'Independent content approval','value':{'decision':'approve','contentVersion':1,'reason':'Synthetic review complete'}},{'schema':'ImportCreate','name':'Payroll tax data boundary','value':{'kind':'payroll_tax','evidenceId':uid(20),'mappingVersion':'DEMO-v1','sourceId':'synthetic-payroll','externalBatchId':'demo-2026-09','cutoffDate':'2026-09-30'}}]})
save('demo-fixtures.json',{'version':1,'synthetic_only':True,'fixture_clock':'2026-09-18T02:00:00Z','isolation':'One run namespace per authenticated demo session; scenarios reset independently. No production data migration.','opening':{'currency':'PHP','journal':[{'account':'Bank','debit':'100000.00','credit':'0.00'},{'account':'Equity','debit':'0.00','credit':'100000.00'}]},'scenarios':[{'id':'DEMO-01','cases':['AC-01','AC-02'],'expected_bank':'111200.00','expected_ar':'0.00','expected_output_tax':'1200.00'},{'id':'DEMO-02','cases':['AC-03','AC-04'],'expected_bank':'89000.00','expected_ap':'0.00','expected_withholding_payable':'200.00'},{'id':'DEMO-03','cases':['AC-01'],'repeat_command':100,'expected_invoice_count':1},{'id':'DEMO-04','cases':['AC-01'],'provider_script':['rejected_invalid_fixture_buyer','new_transport_payload_if_financial_facts_unchanged','accepted'],'original_document_immutable':True},{'id':'DEMO-05','cases':['AC-01','AC-02','AC-07'],'statement_opening':'100000.00','statement_lines':['6000.00','5200.00','-50.00'],'statement_closing':'111150.00','expected_bank':'111150.00'},{'id':'DEMO-06','cases':['AC-01'],'close_task_states':['missing_evidence','reviewed','locked'],'late_post_error':'PERIOD_LOCKED'},{'id':'DEMO-07','cases':['AC-01'],'auditor_scope':'only current demo run and entity','cross_tenant_result':404},{'id':'DEMO-08','cases':[],'concurrent_edit_error':412,'unsaved_input_preserved':True}]})
save('event-contracts.json',{'schema_version':1,'envelope_required':['eventId','eventType','schemaVersion','tenantId','entityId','aggregateType','aggregateId','aggregateVersion','occurredAt','traceId','payload'],'events':{'document.posted.v1':['documentId','journalEntryId','ruleProfileVersion','payloadHash'],'payment.released.v1':['paymentId','releaseKey','channel'],'reconciliation.completed.v1':['reconciliationId','snapshotId'],'period.locked.v1':['periodId','closeVersion','reportSnapshotIds'],'transmission.status_changed.v1':['jobId','documentId','state','evidenceId'],'evidence.available.v1':['evidenceId','sha256'],'rule.activated.v1':['ruleProfileId','version','effectiveFrom']},'consumer_invariants':['authorize scope before dereference','deduplicate consumer plus eventId','no automatic financial side effect without approved command/schedule authority','persist error and owned dead-letter task','unknown schema version quarantined']})
print('Finalized',len(deps),'release increments and',len(tickets),'tickets')
